version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 5000:5000

  client:
    depends_on:
      - backend
    build: ./client
    env_file: ./client/.env
    ports:
      - 3000:80